# Generated by Django 3.1.2 on 2021-03-06 09:45

import autoslug.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(default='explore to find more about my capabilities', max_length=100)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics')),
            ],
            options={
                'verbose_name_plural': 'All fashions',
            },
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(default='explore to find more about my capabilities', max_length=100)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics')),
            ],
            options={
                'verbose_name_plural': 'Graphics',
            },
        ),
    ]
