# Generated by Django 3.1.2 on 2021-03-07 09:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='photo_one',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='photo_three',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='photo_two',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='graphic',
            name='photo_one',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='graphic',
            name='photo_three',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='graphic',
            name='photo_two',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
    ]
