# Generated by Django 3.1.2 on 2021-03-07 10:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210307_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='photo_four',
            field=imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics'),
        ),
    ]
