# Generated by Django 3.1.2 on 2021-04-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fashion_photo_four'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='photo_four',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='photo_three',
        ),
    ]
