# Generated by Django 3.1.2 on 2021-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210408_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='description',
            field=models.TextField(default='Be trendy for every Mood at Braams Fashion Hub'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='overview',
            field=models.CharField(default='Be trendy for every Mood at Braams Fashion Hub', max_length=100),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='description',
            field=models.TextField(default='Be trendy for every Mood at Braams Graphics'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='overview',
            field=models.CharField(default='Be trendy for every Mood at BraamsGraphics', max_length=100),
        ),
    ]
