# Generated by Django 3.1.2 on 2021-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210408_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='description',
            field=models.TextField(blank=True, default='Be trendy for every Mood at Braams Fashion Hub', null=True),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='description',
            field=models.TextField(blank=True, default='Be trendy for every Mood at Braams Graphics', null=True),
        ),
    ]
